
services:
  - type: web
    name: esp32-whisper-server
    env: python
    plan: free
    buildCommand: ""
    startCommand: "python server.py"
    envVars:
      - key: OPENAI_API_KEY
        sync: false
